MODEL = "sentence_transformer_multilingual"
DEFAULT_TRESHOLD = 0.2
DEFAULT_BATCHSIZE = VAR_BATCHSIZE
DEFAULT_WINDOW = VAR_WINDOW
TEST_RESTRICTION_MAX_BATCHES = VAR_MAX_BATCHES
PROCESSORS_COUNT = VAR_PROCESSORS_COUNT
