# MODEL = "sentence_transformer_multilingual_xlm_100"
MODEL = "sentence_transformer_multilingual"
# MODEL = "sentence_transformer_multilingual_labse"
# MODEL = "use_multilingual_v3"
DEFAULT_TRESHOLD = 0.2
DEFAULT_BATCHSIZE = 50
DEFAULT_WINDOW = 40
TEST_RESTRICTION_MAX_BATCHES = 26
PROCESSORS_COUNT = 4